spring.application.name=productHandler

## database related configuration
spring.datasource.url =jdbc:sqlserver://DEEPANSHU-PRASH\\SQLEXPRESS;databaseName=JavaTrainee;encrypt=true;trustServerCertificate=true;
spring.datasource.username=deepanshu
spring.datasource.password=Newgen@01
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.use_sql_comments=true


## for auth server
##spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/master/protocol/openid-connect/certs
logging.config=classpath:logback-spring.xml

## for actuators

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
